import { type NextPage } from "next";
import { signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>My Portal</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="flex items-center justify-between bg-[#2e026d] p-4">
        <nav className="flex gap-6">
          <a href="#" className="group font-navigation">
            <button className="rounded-[14px] py-[10px] px-[20px] group-hover:border-white group-hover:bg-white group-hover:bg-opacity-20 group-hover:shadow-md">
              <p className="text-sm font-bold text-white opacity-70 group-hover:opacity-100">
                Products
              </p>
            </button>
          </a>
          <a href="#" className="group font-navigation">
            <button className="rounded-[14px] py-[10px] px-[20px] group-hover:border-white group-hover:bg-white group-hover:bg-opacity-20 group-hover:shadow-md">
              <p className="text-sm font-bold text-white opacity-70 group-hover:opacity-100">
                Solutions
              </p>
            </button>
          </a>
          <a href="#" className="group font-navigation">
            <button className="rounded-[14px] py-[10px] px-[20px] group-hover:border-white group-hover:bg-white group-hover:bg-opacity-20 group-hover:shadow-md">
              <p className="text-sm font-bold text-white opacity-70 group-hover:opacity-100">
                About Us
              </p>
            </button>
          </a>
          <a href="#" className="group font-navigation">
            <button className="rounded-[14px] py-[10px] px-[20px] group-hover:border-white group-hover:bg-white group-hover:bg-opacity-20 group-hover:shadow-md">
              <p className="text-sm font-bold text-white opacity-70 group-hover:opacity-100">
                Pricing
              </p>
            </button>
          </a>
        </nav>
      </header>
      <main className="flex min-h-screen flex-col bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="mx-[100px] mt-20 flex justify-between gap-10">
          <div className="group relative max-w-[360px] flex-1">
            <div className="absolute inset-0 z-0 h-[426px] w-full origin-top-left -rotate-[10deg] transform rounded-md rounded-b-[60px] rounded-r-[60px] bg-gradient-to-br from-[#6CCFEE]/50 to-[#4C7FE4]/50 p-4 transition duration-[500ms] group-hover:skew-x-[5deg] group-hover:-skew-y-[5deg] group-hover:scale-x-[0.8]"></div>
            <div className="z-10 h-[426px] min-w-[240px] rounded-md rounded-b-[60px] rounded-r-[60px] bg-[#1F1F47] bg-opacity-60 bg-clip-padding py-[50px] px-[20px] backdrop-blur-[40px] backdrop-filter">
              <p className="text-center font-navigation text-sm font-semibold text-white text-opacity-70">
                BASIC
              </p>
              <h1 className="text-center font-navigation text-[60px] text-white">
                Free
              </h1>
              <p className="text-center font-navigation text-sm font-semibold text-white text-opacity-70">
                Trial
              </p>
              <div className="mx-auto mt-[23px] mb-0 grid w-fit gap-y-2">
                <div>
                  <p className="text-sm text-white text-opacity-70">
                    <span className="font-bold">Free</span> Courses
                  </p>
                </div>
                <div>
                  <p className="text-sm text-white text-opacity-70">
                    <span className="font-bold">5 Premium</span> Videos
                  </p>
                </div>
                <div>
                  <p className="text-sm text-white text-opacity-70">
                    <span className="font-bold">Notify me</span>, Favourite
                  </p>
                </div>
              </div>
            </div>
          </div>
          <div className="group relative max-w-[360px] flex-1">
            <div className="absolute inset-0 z-0 h-[519px] w-full origin-bottom-left skew-y-[10deg] transform rounded-md rounded-t-[60px] rounded-r-[60px] bg-gradient-to-br from-[#2FB8FF] to-[#9EECD9] p-4 transition duration-[500ms] group-hover:-skew-x-[5deg] group-hover:skew-y-[15deg] group-hover:scale-x-[0.8]"></div>
            <div className="z-10 h-[519px] min-w-[240px] rounded-md rounded-t-[60px] rounded-r-[60px] bg-[#1F1F47] bg-opacity-60 bg-clip-padding py-[50px] px-[20px] backdrop-blur-[40px] backdrop-filter">
              <p className="text-center font-navigation text-sm font-semibold text-white text-opacity-70">
                PRO
              </p>
            </div>
          </div>
          <div className="group relative max-w-[360px] flex-1">
            <div className="absolute inset-0 z-0 h-[426px] w-full origin-top-right rotate-[10deg] transform rounded-md rounded-b-[60px] rounded-l-[60px] bg-gradient-to-br from-[#73B8F9] to-[#CBD8F1] p-4 transition duration-[500ms] group-hover:-skew-x-[5deg] group-hover:skew-y-[5deg] group-hover:scale-x-[0.8]"></div>
            <div className="z-10 h-[426px] min-w-[240px] rounded-md rounded-b-[60px] rounded-l-[60px] bg-[#1F1F47] bg-opacity-60 bg-clip-padding py-[50px] px-[20px] backdrop-blur-[40px] backdrop-filter"></div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;

const AuthShowcase = () => {
  const { data: sessionData } = useSession();
  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && (
          <span>
            Logged in as {sessionData.user?.name}.{" "}
            {sessionData.user?.phoneNumber}. {sessionData.user?.company}.{" "}
            {sessionData.user?.professionalRole}
          </span>
        )}
      </p>
      <button className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20">
        {sessionData ? (
          //void: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/void
          <span onClick={() => void signOut()}>Sign out</span>
        ) : (
          <Link href="/sign-in">Sign in</Link>
        )}
      </button>
    </div>
  );
};
