import { type NextPage } from "next";
import { signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>My Portal</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="flex items-center justify-between bg-[#2e026d] p-4">
        <nav className="flex gap-6">
          <a href="#" className="group font-navigation">
            <button className="group-hover:border-white rounded-[14px] py-[10px] px-[20px] group-hover:bg-white group-hover:bg-opacity-20 group-hover:shadow-md">
              <p className="text-sm font-bold text-white opacity-70 group-hover:opacity-100">
                Products
              </p>
            </button>
          </a>
          <a href="#" className="group font-navigation">
            <button className="group-hover:border-white rounded-[14px] py-[10px] px-[20px] group-hover:bg-white group-hover:bg-opacity-20 group-hover:shadow-md">
              <p className="text-sm font-bold text-white opacity-70 group-hover:opacity-100">
                Solutions
              </p>
            </button>
          </a>
          <a href="#" className="group font-navigation">
            <button className="group-hover:border-white rounded-[14px] py-[10px] px-[20px] group-hover:bg-white group-hover:bg-opacity-20 group-hover:shadow-md">
              <p className="text-sm font-bold text-white opacity-70 group-hover:opacity-100">
                About Us
              </p>
            </button>
          </a>
          <a href="#" className="group font-navigation">
            <button className="group-hover:border-white rounded-[14px] py-[10px] px-[20px] group-hover:bg-white group-hover:bg-opacity-20 group-hover:shadow-md">
              <p className="text-sm font-bold text-white opacity-70 group-hover:opacity-100">
                Pricing
              </p>
            </button>
          </a>
        </nav>
      </header>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]"></main>
    </>
  );
};

export default Home;

const AuthShowcase = () => {
  const { data: sessionData } = useSession();
  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && (
          <span>
            Logged in as {sessionData.user?.name}.{" "}
            {sessionData.user?.phoneNumber}. {sessionData.user?.company}.{" "}
            {sessionData.user?.professionalRole}
          </span>
        )}
      </p>
      <button className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20">
        {sessionData ? (
          //void: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/void
          <span onClick={() => void signOut()}>Sign out</span>
        ) : (
          <Link href="/sign-in">Sign in</Link>
        )}
      </button>
    </div>
  );
};
